version: "3.8"

services:
  ladder_backend:
    container_name: ladder_backend
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://eli:password@192.168.1.11:5432/ladder_db
      - JWT_SECRET=your_super_secret_jwt_key_change_this_to_something_long_and_random_123456789
      - NODE_ENV=development
      - TZ=Pacific/Auckland
      - EMAIL_USER=eli.murr04@gmail.com
      - EMAIL_PASS=password
