FROM node:lts-jod

WORKDIR /app

COPY package.json ./

RUN npm install

COPY config ./config
COPY controllers ./controllers
COPY middleware ./middleware
COPY routes ./routes
COPY schema.sql ./schema.sql
COPY server.js ./server.js


EXPOSE 5000

CMD ["node", "server.js"]